### ISSUE TITLE
PrintsApi get_prints() results in a 500 error

### ISSUE THREAD

**Issue by mrgaaron** [carbon3d/carbon3d-api#1]
Hi all, I work at Fast Radius and we're getting started with your API.  I ran into an issue where listing prints results in a 500.

Steps to reproduce:

```
import carbon3d as carbon
with open('carbon.jwt', 'r') as fh: jwt = fh.read().strip('\n') #assumes a file with the JWT in it
config = carbon.Configuration()
config.access_token = jwt
api = carbon.PrintsApi(carbon.ApiClient(config))
api.get_prints(limit=10, offset=0)
```

which results in:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronbrenzel/miniconda3/lib/python3.7/site-packages/carbon3d/api/prints_api.py", line 68, in get_prints
    return self.get_prints_with_http_info(limit, offset, **kwargs)  # noqa: E501
  File "/Users/aaronbrenzel/miniconda3/lib/python3.7/site-packages/carbon3d/api/prints_api.py", line 190, in get_prints_with_http_info
    collection_formats=collection_formats)
  File "/Users/aaronbrenzel/miniconda3/lib/python3.7/site-packages/carbon3d/api_client.py", line 370, in call_api
    _preload_content, _request_timeout, _host)
  File "/Users/aaronbrenzel/miniconda3/lib/python3.7/site-packages/carbon3d/api_client.py", line 189, in __call_api
    raise e
  File "/Users/aaronbrenzel/miniconda3/lib/python3.7/site-packages/carbon3d/api_client.py", line 186, in __call_api
    _request_timeout=_request_timeout)
  File "/Users/aaronbrenzel/miniconda3/lib/python3.7/site-packages/carbon3d/api_client.py", line 394, in request
    headers=headers)
  File "/Users/aaronbrenzel/miniconda3/lib/python3.7/site-packages/carbon3d/rest.py", line 235, in GET
    query_params=query_params)
  File "/Users/aaronbrenzel/miniconda3/lib/python3.7/site-packages/carbon3d/rest.py", line 225, in request
    raise ApiException(http_resp=r)
carbon3d.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'X-DNS-Prefetch-Control': 'off', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Download-Options': 'noopen', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '21', 'ETag': 'W/"15-rUPI6uGgW9+TtkAOp/fzydhUejc"', 'Date': 'Tue, 23 Jun 2020 20:48:33 GMT', 'Connection': 'keep-alive'})
HTTP response body: failed to list prints
```

A very similar set of calls with the `PrintersApi` does work correctly.

**Comment by jens-carbon** [comment]
Hi @mrgaaron - we're excited that you're using our API during Early Access. From looking at our logs you are hitting a known issue affecting customers with many prints. We are working on a fix and I will update this ticket once a fix is deployed.

In the meantime, you can work around the issue by limiting the time range:
- Ensure you install the latest API client (`pip3 install carbon3d-client==0.0.6`)
- change your last line to: `print(api.get_prints(limit=10, offset=0, finished_after='2020-03-01'))`

**Comment by jens-carbon** [comment]
@mrgaaron we just deployed a change that should address this issue. Thank you for reporting!
