### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'append`

### ISSUE THREAD

**Issue by scott16lloyd** [carbon3d/carbon3d-api#7]
When using v1\python_examples\printed_parts_csv_exporter.py.
```bash
C:\Users\SLloyd2\Desktop\Carbon_Web_API\v1\python_examples\printed_parts_csv_exporter.py:45: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if client_version < version("0.2.2"):
Traceback (most recent call last):
  File "C:\Users\SLloyd2\Desktop\Carbon_Web_API\v1\python_examples\printed_parts_csv_exporter.py", line 219, in <module>
    main()
  File "C:\Users\SLloyd2\Desktop\Carbon_Web_API\v1\python_examples\printed_parts_csv_exporter.py", line 213, in main
    exporter.export_printed_parts(
  File "C:\Users\SLloyd2\Desktop\Carbon_Web_API\v1\python_examples\printed_parts_csv_exporter.py", line 74, in export_printed_parts
    prints = self.get_prints(printed_parts.print_id.unique().tolist())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SLloyd2\Desktop\Carbon_Web_API\v1\python_examples\printed_parts_csv_exporter.py", line 142, in get_prints   
    prints = prints.append(print_record.to_dict(), ignore_index=True)
             ^^^^^^^^^^^^^
  File "C:\Users\SLloyd2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?
```

**Comment by w3dot0** [comment]
@scott16lloyd, thank you for bringing this to our attention. The issue appears to be due to our csv export example relying on the 1.x version of pandas, since the `.append` method isn't available in version 2.x. 

For a quick fix, I suggest you install version 1.x of pandas. You can do this by using the command `pip3 install pandas==1.*` Please let us know if this resolves the issue for you.

**Comment by jens-carbon** [comment]
@scott16lloyd, thank you for bringing this to our attention. The issue appears to be due to our csv export example relying on the 1.x version of pandas, since the `.append` method isn't available in version 2.x. 

For a quick fix, I suggest you install version 1.x of pandas. You can do this by using the command `pip3 install pandas==1.*` Please let us know if this resolves the issue for you.
